COMMON_MSGS_STEREO_MSGS_SOURCE = $(COMMON_MSGS_SOURCE)
COMMON_MSGS_STEREO_MSGS_SITE = $(COMMON_MSGS_SITE)
COMMON_MSGS_STEREO_MSGS_LICENSE = $(COMMON_MSGS_LICENSE)
COMMON_MSGS_STEREO_MSGS_LICENSE_FILES = $(COMMON_MSGS_LICENSE_FILES)
COMMON_MSGS_STEREO_MSGS_INSTALL_STAGING=YES

COMMON_MSGS_STEREO_MSGS_DEPENDENCIES = $(COMMON_MSGS_ALL_DEPENDENCIES)

COMMON_MSGS_STEREO_MSGS_SUBDIR = stereo_msgs

$(eval $(catkin-package))
