AMENT_CMAKE_VERSION = 0.7.3
AMENT_CMAKE_SOURCE = $(AMENT_CMAKE_VERSION).tar.gz
AMENT_CMAKE_SITE = https://github.com/ament/ament_cmake/archive
AMENT_CMAKE_LICENSE = BSD3
AMENT_CMAKE_LICENSE_FILES = LICENSE

AMENT_CMAKE_CONF_OPTS += -DPYTHON_VERSION=$(PYTHON_VERSION)

ROS_INSTALL_PREFIX=/opt/ros

include $(sort $(wildcard $(BR2_EXTERNAL_ROS_PATH)/package/ament_cmake/*/*.mk))
