COMMON_MSGS_NAV_MSGS_SOURCE = $(COMMON_MSGS_SOURCE)
COMMON_MSGS_NAV_MSGS_SITE = $(COMMON_MSGS_SITE)
COMMON_MSGS_NAV_MSGS_LICENSE = $(COMMON_MSGS_LICENSE)
COMMON_MSGS_NAV_MSGS_LICENSE_FILES = $(COMMON_MSGS_LICENSE_FILES)
COMMON_MSGS_NAV_MSGS_INSTALL_STAGING=YES

COMMON_MSGS_NAVY_MSGS_DEPENDENCIES = $(COMMON_MSGS_ALL_DEPENDENCIES)

COMMON_MSGS_NAV_MSGS_SUBDIR = nav_msgs

$(eval $(catkin-package))
