COMMON_MSGS_ACTIONLIB_MSGS_SOURCE = $(COMMON_MSGS_SOURCE)
COMMON_MSGS_ACTIONLIB_MSGS_SITE = $(COMMON_MSGS_SITE)
COMMON_MSGS_ACTIONLIB_MSGS_LICENSE = $(COMMON_MSGS_LICENSE)
COMMON_MSGS_ACTIONLIB_MSGS_LICENSE_FILES = $(COMMON_MSGS_LICENSE_FILES)
COMMON_MSGS_ACTIONLIB_MSGS_INSTALL_STAGING=YES

COMMON_MSGS_ACTIONLIB_MSGS_DEPENDENCIES = $(COMMON_MSGS_ALL_DEPENDENCIES)

COMMON_MSGS_ACTIONLIB_MSGS_SUBDIR = actionlib_msgs

$(eval $(catkin-package))
