COMMON_MSGS_VISUALIZATION_MSGS_SOURCE = $(COMMON_MSGS_SOURCE)
COMMON_MSGS_VISUALIZATION_MSGS_SITE = $(COMMON_MSGS_SITE)
COMMON_MSGS_VISUALIZATION_MSGS_LICENSE = $(COMMON_MSGS_LICENSE)
COMMON_MSGS_VISUALIZATION_MSGS_LICENSE_FILES = $(COMMON_MSGS_LICENSE_FILES)
COMMON_MSGS_VISUALIZATION_MSGS_INSTALL_STAGING=YES

COMMON_MSGS_VISUALIZATION_MSGS_DEPENDENCIES = $(COMMON_MSGS_ALL_DEPENDENCIES)

COMMON_MSGS_VISUALIZATION_SUBDIR = visualization_msgs

$(eval $(catkin-package))
